### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [sidlatau/flutter_document_picker#2]
Android Gradle build fails. I have done all the digging Gradle allows to and this is the most useful information I could get out of it:

```
Using incremental javac compilation for :flutter_document_picker debug.
Using incremental javac compilation for :flutter_document_picker debugUnitTest.
Using incremental javac compilation for :flutter_document_picker release.
Using incremental javac compilation for :flutter_document_picker releaseUnitTest.
Using incremental javac compilation for :flutter_document_picker debugAndroidTest.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_document_picker'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)
```

The Gradle `--scan` also shows this:

```
Failed to notify project evaluation listener.
> (No message provided)

org.gradle.api.ProjectConfigurationException:  A problem occurred configuring project ':flutter_document_picker'.

Caused by:  org.gradle.internal.event.ListenerNotificationException: 
Failed to notify project evaluation listener.

Caused by: java.lang.AbstractMethodError: 
(No message provided)
at org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt.resolveSubpluginArtifacts(KotlinPlugin.kt:780)
at org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt.loadSubplugins(KotlinPlugin.kt:754)
at org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt.access$loadSubplugins(KotlinPlugin.kt:1)
at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$handleProject$2.execute(KotlinPlugin.kt:551)
at org.jetbrains.kotlin.gradle.plugin.AbstractAndroidProjectHandler$handleProject$2.execute(KotlinPlugin.kt:496)
at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
```

**Comment by creativecreatorormaybenot** [comment]
After some research I figured that some Kotlin method must be missing in the Kotlin version I am using compared to the Kotlin version the plugin is using because of the *`AbstractMethodError` of `org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt.resolveSubpluginArtifacts`*.  
Upgrading the **`ext.kotlin_version`** in `build.gradle` `android` project level to **`1.2.61`** solved the issue.
