### ISSUE TITLE
Unable to determine Swift version

### ISSUE THREAD

**Issue by RohithKilaparthi** [sidlatau/flutter_document_picker#28]
When I try to execute 'flutter run' command, there is an error which says 
```
[!] Unable to determine Swift version for the following pods:
- `flutter_document_picker` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the
`SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
``` 
Flutter doctor doesn't quote any errors. Please look into the error and help me in resolving the error.

***flutter run output***
```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...                                              1.0s

CocoaPods' output:

↳

      Preparing



    Analyzing dependencies



    Inspecting targets to integrate

      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)



    Fetching external sources

    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`

    -> Fetching podspec for `flutter_document_picker` from `.symlinks/plugins/flutter_document_picker/ios`

    -> Fetching podspec for `flutter_full_pdf_viewer` from `.symlinks/plugins/flutter_full_pdf_viewer/ios`

    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`

    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`

    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`

    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`



    Resolving dependencies of `Podfile`



    Comparing resolved specification to the sandbox manifest

      A FMDB

      A Flutter

      A flutter_document_picker

      A flutter_full_pdf_viewer

      A path_provider

      A shared_preferences

      A sqflite

      A url_launcher



    Downloading dependencies



    -> Installing FMDB (2.7.5)

      > Copying FMDB from `/Users/akki/Library/Caches/CocoaPods/Pods/Release/FMDB/2.7.5-2ce00` to `Pods/FMDB`



    -> Installing Flutter (1.0.0)



    -> Installing flutter_document_picker (0.0.1)



    -> Installing flutter_full_pdf_viewer (1.0.1)



    -> Installing path_provider (0.0.1)



    -> Installing shared_preferences (0.0.1)



    -> Installing sqflite (0.0.1)



    -> Installing url_launcher (0.0.1)

      - Running pre install hooks

    [!] Unable to determine Swift version for the following pods:



    - `flutter_document_picker` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the

    `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.



    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:578:in `validate_targets'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:158:in `install!'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/command/install.rb:51:in `run'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/bin/pod:22:in `load'

    /usr/local/Cellar/cocoapods/1.7.4/libexec/bin/pod:22:in `<main>'



Error output from CocoaPods:

↳



    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and

    the unknown UUID is being discarded.



    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See

    `https://guides.cocoapods.org/syntax/podfile.html#platform`.



Error running pod install

Error launching application on iPhone Xʀ.

**Comment by RohithKilaparthi** [comment]
@sidlatau Can you look into the issue and help us in fixing the issue?

**Comment by sidlatau** [comment]
Several issues with the same error are already closed. Check this:
https://github.com/sidlatau/flutter_document_picker/issues/26#issuecomment-497457035

**Comment by RohithKilaparthi** [comment]
Thanks, it worked.
